repos:
        - repo: local
          hooks:
                  - id: style_fix
                    name: Style Fix
                    description: This hook fixes styling 3.
                    entry: bash -c '(cd format-1; npm run style:fix) && git add -A' --
                    language: system
