repos:
        - repo: local
          hooks:
                  - id: style_fix
                    name: Style Fix
                    description: This hook fixes styling.
                    entry: bash -c '(cd format-1; npm run style:fix)' --
                    language: system
